spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: walletuser
    password: walletpass

  data:
    redis:
      host: localhost
      port: 6379
      password: redispass
      timeout: 2000ms

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: wallet-service-dev
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
         spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
         spring.json.trusted.packages: org.fintech.wallet.dto.event
         spring.json.value.default.type: org.fintech.wallet.dto.event.WalletEvent
         spring.json.use.type.headers: false



management:
  prometheus:
    metrics:
      export:
        enabled: true
security:
  jwt:
    secret: dev-secret-key-for-jwt-token-signing
    expiration: 3600000
    refresh-expiration: 604800000

cloudinary:
  cloud-name: 
  api-key: 
  api-secret: 

logging:
  level:
    com.fintech.wallet: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG
    org.springframework.kafka: DEBUG
